name: Build and Publish Image
run-name: Pushing new Imperial College Notes Devcontainer by @${{ github.actor }} 
on:
  push:
    branches:
      - enh/development-docker
    paths:
      - '.devcontainer/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .devcontainer/Dockerfile
          sparse-checkout-cone-mode: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Enrich Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/oliverkillane/imperial-computing-notes-dev
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          flavor: |
            latest=true
          labels: |
            org.opencontainers.image.description=A development image for the imperial computing notes
            org.opencontainers.image.vendor=Imperial Computing Notes
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.IMPERIAL_NOTES_GHCR_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max